version: '3.8'

services:
  web:
    build: ./server   # Path to the server directory (you might need to adjust this)
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=production

  frontend:
    build: ./public    # Path to your public (frontend) directory
    ports:
      - "8080:8080"
    volumes:
      - ./public:/app
    environment:
      - NODE_ENV=production
